spring:
  jpa:
    database: mysql   # ?? ?? ??
    show-sql: true
    properties:
      format_sql: true
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/book_store?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234!!



